name: Validate
on: [push]
jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      # Setup node
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          # Using node action to manage caching node_modules
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: ESLint
        run: yarn lint

      - name: Build site
        run: yarn build
